### ISSUE TITLE
/ would be better if it didn't use the built in search dialog

### ISSUE THREAD

**Issue by nosami** [nosami/XSVim#44]
... then there would be no need to escape to stop searching.. It could also be used in combination with other commands such as `d/search`

**Comment by dlprows** [comment]
+1. would also make n/N work with searching

**Comment by nosami** [comment]
`n/N` should be working now with the built in search dialog. Will definitely make sure that they still work after I make this change :)

**Comment by dlprows** [comment]
last time i tested `n/N` with `*` it wasn't working, but that could be separate from `/` searching

**Comment by dlprows** [comment]
I just checked. `n/N` does work, but the built in search dialog keeps focus, so when i do `/something<CR>` the search dialog still has focus, so when i then press `n` i'm now searching for "somethingn"
If i press escape to get focus out of the search dialog, then `n/N` work as expected.
moving away from the built in search dialog would make it so that manually removing focus from the search dialog wouldn't be required.

**Comment by nosami** [comment]
> If i press escape to get focus out of the search dialog, then n/N work as expected.

Yeah, I'm afraid that's just how it is right now. That's partly what this work will solve hopefully!
